### ISSUE TITLE
Known Issues Tracker

### ISSUE THREAD

**Issue by folke** [folke/noice.nvim#6]
- [x] https://github.com/neovim/neovim/issues/17810 
  - Incsearch loses highlights during redraw
  - 🪓  we disable `conceallevel` during search
- [ ] https://github.com/neovim/neovim/issues/20416
  - redraw triggers last messages to `ext_messages`
  - 🪓  we wrap redraw, ignore messages and check for ui updates
- [ ] https://github.com/neovim/neovim/issues/20311
  - we need to know when state will become blocking
  - 🪓  we wrap input functions so we know blocking input is coming
- [x] https://github.com/neovim/neovim/issues/20309
  - we need a way to control the visible cursor without switching windows/buffers/cursors
  - 🪓  we render fake cursors instead
- [ ] plugins that rely on the cmdline position (like `cmp`) don't know the real cmdline position
  - 🪓 **Noice** fixes this for [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) 
- [x] https://github.com/folke/noice.nvim/issues/17
- [x] https://github.com/neovim/neovim/issues/20463
  - [ ] https://github.com/neovim/neovim/pull/27950
  - moving the cursor during `substitute` does not update the **cmdline ui**
  - 🪓 we do `vim.api.nvim_input("<space><bs>")` during substitute to force a redraw
- [x] https://github.com/neovim/neovim/issues/20462
  - first echo has the wrong kind
- [x] https://github.com/rcarriga/nvim-notify/issues/137 
  - nvim-notify does not wrap notifications
- [x] https://github.com/neovim/neovim/issues/20715

**Comment by ilan-schemoul** [comment]
Another known issue acknowledged by the neovim's team is that this plugin might lead to assert failures (and so crash on startup). See https://github.com/neovim/neovim/issues/28331.

By the way the readme reads "It is highly recommended to use Neovim nightly, since a bunch of issues have already been fixed upstream." however nightly releases are shipped with RelWithDebInfo mode which (I believe but cannot find documentation about this) enables assertions checks which might fail because of Noice (I have checked that Release mode doesn't crash but RelWithDebInfo crashes)

**Comment by justinmk** [comment]
> however nightly releases are shipped with RelWithDebInfo mode which (I believe but cannot find documentation about this) enables assertions checks which might fail because of Noice

Assertions declare conditions that "cannot happen". Without the assertions, behavior is just undefined and may silently lead to very weird and potentially destructive situations.

**Comment by bew** [comment]
Hum this looks like a mistake 🤔

**Comment by dbieber-rfideas** [comment]
> Another known issue acknowledged by the neovim's team is that this plugin might lead to assert failures (and so crash on startup). See [neovim/neovim#28331](https://github.com/neovim/neovim/issues/28331).
> 
> By the way the readme reads "It is highly recommended to use Neovim nightly, since a bunch of issues have already been fixed upstream." however nightly releases are shipped with RelWithDebInfo mode which (I believe but cannot find documentation about this) enables assertions checks which might fail because of Noice (I have checked that Release mode doesn't crash but RelWithDebInfo crashes)

Does anyone know what we can do about this? I am not finding solutions, but maybe I am missing something. I am ok nerfing Noice if that is required, but would prefer not to completely disable the plugin. I've tried the latest nightly as of today and it's still crashing with the latest version of Noice from Lazy.

**Comment by insidewhy** [comment]
One more, I'm not sure if it's a bug or an issue with my configuration. I'm using neovim nightly from two nights ago and when I record a macro I don't get any notification.

**Comment by folke** [comment]
@insidewhy check the docs. You can either get a notification or just add it to lualine

**Comment by JohnWilliston** [comment]
I have a similar problem, but I don't merely not get the notification: the recording doesn't work. Nothing is recorded.

**Comment by folke** [comment]
@JohnWilliston noice doesn't interfere or interact with recording macros in any way, so 10000% something in your config unrelated to noice.

**Comment by JohnWilliston** [comment]
> @JohnWilliston noice doesn't interfere or interact with recording macros in any way, so 10000% something in your config unrelated to noice.

I don't know how to reconcile that with the fact that macros don't record when I'm using Noice notifications and do work when I'm not. I like Noice a lot, but I don't like it enough to give up macro recording.

**Comment by liubog2008** [comment]
> plugins that rely on the cmdline position (like cmp) don't know the real cmdline position

**Comment by ilan-schemoul** [comment]
I have tried to follow discussions on 0.11 related issues and it seems like a lot of issues have been resolved. I do not see any recent update of the top post and 0.11 just released.

I used to use Noice but realized after months of bad experience of many crashs and freeze of nvim I found out it was only because of Noice.
I want to specifically know if there is any possibility Noice can cause any stability issue with nvim 0.11 before trying again.

This post mentions technical details such as 
> 🪓 we wrap input functions so we know blocking input is coming

but I think more than implementation detail we might want to know the actual consequences (and again, especially, stability issues) of each issue. @folke I hope you can find time to update original post

Noice is beautiful, I'm very willing to try it again if stability issues are gone.

**Comment by JohnWilliston** [comment]
> Noice is beautiful, I'm very willing to try it again if stability issues are gone.

I realize you weren't asking me, but I started using it again recently and don't have any of the issues I had before. The only issue that remains for me now is perhaps unavoidable. I use the "hydra" plugin to simplify a number of common tasks (e.g., resizing windows, re-positioning windows, navigating windows, etc.) that otherwise have a lot of repetitive key sequences. The hydra plugin gives instructions to the user by displaying text on the messages line at the bottom, and when I'm using noice it effectively "silences" that until _after_ I've finished and dismissed the hydra in question. Only after the text would be useful does it pop up in a notification window. I haven't found a way to fix that yet. But all the other issues I had previously seen with noice have been resolved.

**Comment by Ma94xx** [comment]
@JohnWilliston I'm having the same issue with recording macros. Works perfectly fine when noice is not installed, and it doesn't record anything if noice is active. Can you give me a hint on how you fixed this? Also I noticed, that spell correction  via whichkey is super slow with noice, and quick as usual without noice...

**Comment by JohnWilliston** [comment]
> [@JohnWilliston](https://github.com/JohnWilliston) I'm having the same issue with recording macros. Works perfectly fine when noice is not installed, and it doesn't record anything if noice is active. Can you give me a hint on how you fixed this? Also I noticed, that spell correction via whichkey is super slow with noice, and quick as usual without noice...

Sure. My fix was a tad overkill: I stopped worrying about the normal notification and put together my own indicator on my own custom status line using [the heirline plugin](https://github.com/rebelot/heirline.nvim). You can view [my whole public Neovim configuration here](https://github.com/JohnWilliston/neovim-config?tab=readme-ov-file) if you like. My [heirline spec](https://github.com/JohnWilliston/neovim-config/blob/master/nvim/lua/plugins/ui/heirline.lua) is a particularly bad example of how to code in Lua, as I haven't found the time to clean it up yet, but you'll see exactly what I did there.
